# Generated by Django 3.2.3 on 2021-05-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventtitle', models.CharField(max_length=20)),
                ('Date', models.DateField()),
                ('Time', models.CharField(max_length=20)),
                ('max_no_participants', models.IntegerField()),
                ('Description', models.CharField(max_length=20)),
                ('eventbanner', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='User_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
                ('mobile', models.IntegerField()),
                ('semester', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=10)),
            ],
        ),
    ]
