# Generated by Django 3.2.3 on 2021-05-24 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210523_2346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventdetails',
            options={'verbose_name_plural': 'EventDetails'},
        ),
        migrations.AlterModelOptions(
            name='user_details',
            options={'verbose_name_plural': 'User_Details'},
        ),
    ]
