# Generated by Django 3.2.3 on 2021-05-24 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210524_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetails',
            name='Description',
            field=models.TextField(max_length=20),
        ),
    ]
